//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsianOptions.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AsianOptions.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down growth.
        /// </summary>
        public static string MainWindow_DownGrowth {
            get {
                return ResourceManager.GetString("MainWindow_DownGrowth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise price.
        /// </summary>
        public static string MainWindow_ExercisePrice {
            get {
                return ResourceManager.GetString("MainWindow_ExercisePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string MainWindow_Exit {
            get {
                return ResourceManager.GetString("MainWindow_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MainWindow_File {
            get {
                return ResourceManager.GetString("MainWindow_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial price.
        /// </summary>
        public static string MainWindow_InitialPrice {
            get {
                return ResourceManager.GetString("MainWindow_InitialPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest rate.
        /// </summary>
        public static string MainWindow_InterestRate {
            get {
                return ResourceManager.GetString("MainWindow_InterestRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods.
        /// </summary>
        public static string MainWindow_Periods {
            get {
                return ResourceManager.GetString("MainWindow_Periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Option.
        /// </summary>
        public static string MainWindow_PriceOption {
            get {
                return ResourceManager.GetString("MainWindow_PriceOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save Results.
        /// </summary>
        public static string MainWindow_SaveResults {
            get {
                return ResourceManager.GetString("MainWindow_SaveResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulation Parameters.
        /// </summary>
        public static string MainWindow_SimulationParameters {
            get {
                return ResourceManager.GetString("MainWindow_SimulationParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulations.
        /// </summary>
        public static string MainWindow_Simulations {
            get {
                return ResourceManager.GetString("MainWindow_Simulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asian Options Pricing Simulation (sequential).
        /// </summary>
        public static string MainWindow_Title {
            get {
                return ResourceManager.GetString("MainWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up growth.
        /// </summary>
        public static string MainWindow_UpGrowth {
            get {
                return ResourceManager.GetString("MainWindow_UpGrowth", resourceCulture);
            }
        }
    }
}
